name: CI Tests 🔧

on:
  push:
    paths:
      - "**.ts"
      - "package.json"

concurrency:
  group: "ci"
  cancel-in-progress: true

jobs:
  build:
    name: "CI Testing"
    if: github.repository == '--package-author--/--package-name--'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Activate Corepack"
        run: corepack enable
      - name: "Setup Node v${{ matrix.node }} for ${{ matrix.os }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: "Install Packages"
        run: yarn install
      - name: "Build Module/Tests"
        run: yarn run build
      - name: "Run Tests"
        run: yarn run test
