name: Deploy to NPM/GitHub 🚀

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    name: "Build Module 🚧"
    if: github.repository == '--package-author--/--package-repo--'
    environment: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Activate Corepack"
        run: corepack enable
      - name: "Setup Node v${{ vars.NODE_VERSION }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: yarn
      - name: "Install Packages"
        run: yarn install
      - name: "Build Module"
        run: yarn run build
      - name: "Export Module as Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist
            !dist/tests

  deploy-npm:
    name: "Publish to NPM 🚀"
    environment: Deploy
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Load Artifacts"
        uses: actions/download-artifact@v4
      - name: "Activate Corepack"
        run: corepack enable
      - name: "Setup Node v${{ vars.NODE_VERSION }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"
          token: ${{ secrets.NPM_TOKEN }}
          always-auth: true
          cache: yarn
      - name: ${{fromJSON('{"false":"Publish Package (Dry Run)","true":"Publish Package"}')[!env.ACT]}}
        if: ${{!env.ACT}}
        run: yarn publish --access=public --tag=beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-github:
    name: "Publish to GitHub 🚀"
    environment: Deploy
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Load Artifacts"
        uses: actions/download-artifact@v4
      - name: "Activate Corepack"
        run: corepack enable
      - name: "Setup Node v${{ vars.NODE_VERSION }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          registry-url: "https://npm.pkg.github.com"
          token: ${{ secrets.GITHUB_TOKEN }}
          always-auth: true
          cache: yarn
      - name: ${{fromJSON('{"false":"Publish Package (Dry Run)","true":"Publish Package"}')[!env.ACT]}}
        if: ${{!env.ACT}}
        run: yarn publish --access=public --tag=beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
